keyboardcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # localhost:8000 -> route the request to our main_app
    path('', include('main_app.urls')), 
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # route for keyboards index
  path('keyboards/', views.keyboards_index, name='index'),
  path('keyboards/<int:keyboard_id>/', views.keyboards_detail, name='detail'),
  path('keyboards/<int:keyboard_id>/add_keycap', views.add_keycap, name='add_keycap'),
  path('keyboards/<int:keyboard_id>/add_stablizer/<int:stablizer_id>/', views.add_stablizer, name='add_stablizer'),
  path('keyboards/create/', views.KeyboardCreate.as_view(), name='keyboards_create'),
	path('keyboards/<int:pk>/update/', views.KeyboardUpdate.as_view(), name='keyboards_update'),
	path('keyboards/<int:pk>/delete/', views.KeyboardDelete.as_view(), name='keyboards_delete'),
  path('stablizers/', views.StablizerList.as_view(), name='stablizers_index'),
  path('stablizers/<int:pk>/', views.StablizerDetail.as_view(), name='stablizers_detail'),
  path('stablizers/create/', views.StablizerCreate.as_view(), name='stablizers_create'),
  path('stablizers/<int:pk>/update/', views.StablizerUpdate.as_view(), name='stablizers_update'),
  path('stablizers/<int:pk>/delete/', views.StablizerDelete.as_view(), name='stablizers_delete'),
]


# submit our form
# find the cat from the params id(cat_id), then add the feeding to that cat,
#

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse
from datetime import date

# Create your models here.

class Stablizer(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stablizers_detail', kwargs={'pk': self.id})



class Keyboard(models.Model):
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    switches = models.TextField(max_length=250)
    stablizers = models.ManyToManyField(Stablizer)

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('detail', kwargs={'keyboard_id': self.id})

PROFILES = (
    ('C', 'Cherry'),
    ('O', 'OEM'),
    ('X', 'XDA')
)

class Keycap(models.Model):
    date = models.DateField()
    profile = models.CharField(
        max_length=1,
        # create a select menu, the value of the select item
        # will be the first letter, and whats between the tags,
        # what the user see will be second item in the tuple (Breakfast)
        choices=PROFILES,
        default=PROFILES[0][0]
    )
    # Create a cat_id FK lowercase singular of your related model
    # inside postgres the column will have _id attached so cat_id
    keyboard = models.ForeignKey(Keyboard, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.get_profile_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Keycap


class KeycapForm(ModelForm):
    # Meta describes data about the functionality

    class Meta:
        model = Keycap
        fields = ['date', 'profile']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
# Create your views here.
from django.http import HttpResponse
# import our model
from .models import Keyboard, Stablizer
from .forms import KeycapForm


class KeyboardCreate(CreateView):
    model = Keyboard
    fields = ['name', 'size', 'type', 'switches']  # referring the models field, so what fields do you
    # want to include on the form


class KeyboardUpdate(UpdateView):
    model = Keyboard
    # limit the renaming of the keyboard
    fields = ['size', 'type', 'switches']
    # redirect is happening by the get_absolute url defined


class KeyboardDelete(DeleteView):
    model = Keyboard
    success_url = '/keyboards/'

def add_stablizer(request, keyboard_id, stablizer_id):

  keyboard = Keyboard.objects.get(id=keyboard_id)
  keyboard.stablizers.add(stablizer_id)
  return redirect('detail', keyboard_id=keyboard_id)

def add_keycap(request, keyboard_id):

    # create a modelForm instance that process our request.POST data
    form = KeycapForm(request.POST)
    # validate the form
    if form.is_valid():  # <- the method comes from the FeedingForm class
        # don't save the form to the db, until we add the cat
        # to the feeding
        # pauses saving the form until later,
        new_keycap = form.save(commit=False)
        # but it creates the object we want to put in the database
        # assing the cat_id to the new_feeding (object we want to put in the db)
        # reference line 38-40 in models.py for why new_feeding.cat_id instead of new_feeding.cat
        new_keycap.keyboard_id = keyboard_id
        new_keycap.save()  # this puts the new_feeding into the feeding table

    # reference 'detail' name in the urls.py, cat_id is the <int:cat_id> in the path
    # don't forget to import redirect at the top
    return redirect('detail', keyboard_id=keyboard_id)


def home(request):
    return HttpResponse(request, 'home.html')


def about(request):
    return render(request, 'about.html')

# Add new view


def keyboards_index(request):
    # retrieving all the keyboards from the db
    keyboards = Keyboard.objects.all()
    # 'keyboards' is the name being called in the HTML, keyboards is what we are calling above
    return render(request, 'keyboards/index.html', {'keyboards': keyboards})


def keyboards_detail(request, keyboard_id):
    # find a keyboard by its id, keyboard_id is from the urls.py file for the keyboards_detail route
    keyboard = Keyboard.objects.get(id=keyboard_id)
    stablizers_keyboard_doesnt_have = Stablizer.objects.exclude(id__in = keyboard.stablizers.all().values_list('id'))
    keycap_form = KeycapForm()

    return render(request, 'keyboards/detail.html', {
        'keyboard': keyboard,
        'keycap_form': keycap_form,
        'stablizers': stablizers_keyboard_doesnt_have
    })

class StablizerList(ListView):
  model = Stablizer

class StablizerDetail(DetailView):
  model = Stablizer

class StablizerCreate(CreateView):
  model = Stablizer
  fields = '__all__'

class StablizerUpdate(UpdateView):
  model = Stablizer
  fields = ['name', 'color']

class StablizerDelete(DeleteView):
  model = Stablizer
  success_url = '/stablizers/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Hello! Welcome to my Keyboard Collection!</h1>
<hr />
<p>Be sure to check out all my Keyboard Builds!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Keyboard Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;KeyboardCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <!-- new markup below -->
            <li><a href="{% url 'stablizers_create' %}">Add a Stablizer</a></li>
            <li><a href="{% url 'stablizers_index' %}">View All Stablizers</a></li>
            <li><a href="{% url 'keyboards_create' %}">Add a Keyboard</a></li>
            <li><a href="{% url 'index' %}">View All My Keyboards</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2021 Keyboard Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/keyboards/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Keyboard Details</h1>


<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ keyboard.name }}</span>
        <p>Size: {{ keyboard.size }}</p>
        <p>Type: {{ keyboard.type }}</p>
        {% if keyboard.switches > 0 %}
        <p>Switches: {{ keyboard.switches }}</p>
        {% else %}
        <p>Switches: No Switches</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'keyboards_update' keyboard.id %}">Edit</a>
        <a href="{% url 'keyboards_delete' keyboard.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form method="post" action="{% url 'add_keycap' keyboard.id%}">
      {% csrf_token %} {{ keycap_form.as_p }}
      <input type="submit" class="btn" value="Add Keycaps" />
    </form>

    <table class="striped">
      <thead>
        <tr>
          <th>Date created</th>
          <th>Keycap Profile</th>
        </tr>
      </thead>
      <tbody>
        {% for keycap in keyboard.keycap_set.all %}
        <tr>
          <td>{{keycap.date}}</td>
          <td>{{keycap.get_profile_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
	<hr />
	<div class="row">
	  <div class="col s6">
		<h3>{{ keyboard.name }}'s Stablizers</h3>
		{% if keyboard.stablizers.count %} {% for stablizer in keyboard.stablizers.all %}
		<div class="card">
		  <div class="card-content">
			<span class="card-title">
			  A <span style="color: {{ stablizer.color }}">{{ stablizer.color }}</span> {{stablizer.name }}
			</span>
		  </div>
		</div>
		{% endfor %} {% else %}
		<h5>No more Stablizers</h5>
		{% endif %}
	  </div>
	  <!-- Available toys will come after this line -->
	  <div class="col s6">
		<h3>Available Stablizers</h3>
		{% if stablizers.count %}
		  {% for stablizer in stablizers.all %}
			<div class="card">s
			  <div class="card-content">
				<span class="card-title">
				  A <span style="color: {{ stablizer.color }}">{{ stablizer.color }}</span> {{ stablizer.name }}
				</span>
			  </div>
			  <div class="card-action">
				<form action="{% url 'add_stablizer' keyboard.id stablizer.id %}" method="post">
				  {% csrf_token %}
				  <button type="submit" class="btn">Add</button>
				</form>
			  </div>
			</div>
		  {% endfor %}
		{% else %}
		  <h5>{{keyboard.name}} All Stablizers</h5>
		{% endif %}
	  </div>
	</div>
	

<script>
  // date input
  const dateEl = document.querySelector("#id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  const selectEl = document.getElementById("id_profile");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/keyboards/index.html
{% extends 'base.html' %} {% block content %} {% for keyboard in keyboards %}

<a href="{% url 'detail' keyboard.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ keyboard.name }}</span>
      <p>size: {{ keyboard.size }}</p>
      <p>type: {{ keyboard.type }}</p>
      {% if keyboard.switches > 0 %}
      <p>switches: {{ keyboard.switches }}</p>
      {% else %}
      <p>switches: No Switches</p>
      {% endif %}
    </div>
  </div>
</a>

{% endfor %} {% endblock %}

main_app/templates/main_app/keyboard_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Keyboard</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' keyboard.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/keyboard_form.html
{% extends 'base.html' %}


{% block content %}
  <!-- New if/else block -->
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Keyboard</h1>
  {% endif %}
	  <!-- Leaving the action empty makes the form post to the same url used to display it -->
	  <form action="" method="post">
		<!-- Django requires the following for security purposes -->
		{% csrf_token %}
		<table>
		  <!-- Render the inputs inside of <tr>s & <td>s -->
		  {{ form.as_table }}
		</table>
		<input type="submit" value="Submit!" class="btn">
	  </form>
{% endblock %}

main_app/templates/main_app/stablizer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Stablizer</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'stablizers_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/stablizer_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Stablizer Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ stablizer.name }}</span>
        <p>Color: {{ stablizer.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'stablizers_update' stablizer.id %}">Edit</a>
        <a href="{% url 'stablizers_delete' stablizer.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/stablizer_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Stablizer</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/stablizer_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Stablizer List</h1>

{% for stablizer in stablizer_list %}
  <a href="{% url 'stablizers_detail' stablizer.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ stablizer.name }}</span>
            <p>Color: {{ stablizer.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}